[application]
name = "Octoscope"
default_platform = "desktop"

[web.app]

# HTML title tag content
title = "Octoscope"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
publisher = "lambdalisue"
identifier = "com.lambdalisue.Octoscope"

[bundle.macos]
info_plist_path = "assets/mac/Info.plist"
files = {}
hardened_runtime = true
