[application]
name = "Arto"
default_platform = "desktop"

[web.app]

# HTML title tag content
title = "Arto"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.lambdalisue.Arto"
publisher = "lambdalisue"
icon = ["extras/mac/arto-app.icns"]
copyright = "Copyright 2025 lambdalisue"
category = "Utility"
short_description = "A GitHub Markdown viewer"
long_description = """
Arto is a GitHub Markdown viewer built with Dioxus.
"""

[bundle.macos]
license = "LICENSE"
provider_short_name = "Alisue"
info_plist_path = "extras/mac/Info.plist"
files = {}
hardened_runtime = true
